### ISSUE TITLE
Github Action's deprecation warnings : Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by laurentvasseurtekos** [tommykw/pull-request-reviewer-reminder-action#450]
Hello, thank you for this Github action, it is really useful.

I would like to notice that since this github action update [GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), the action is generating a warning : 

![image](https://user-images.githubusercontent.com/96220327/208012543-d4d33dc4-0490-4c93-acac-f2f86f56ec16.png)

Have a good day

**Comment by tommykw** [comment]
@laurentvasseurtekos 
Thank you for letting me know. I have fixed it in the following version.
`tommykw/pull-request-reviewer-reminder-action@v2`
